package np3;

import java.awt.FileDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : NotePad
//  @ File Name : NoteActionListener.java
//  @ Date : 2019-08-07
//  @ Author : jinhyun Park
//
//




public class NoteActionListener implements ActionListener {
	private NotePad3 frm;
	private String cmd;
	private FileDialog fd=null;
	
	
	public NoteActionListener(NotePad3 frm, FileDialog fd) {   // <- 생성자
		this.frm=frm;
		this.fd=fd;
	}

	
	public void actionPerformed(ActionEvent ae) {
		cmd=ae.getActionCommand();
		String filename=null;
		if(cmd.equals("열기")) {
			fd.setTitle("읽을 파일을 선택하세요.");
			fd.setVisible(true);
			filename=fd.getDirectory()+fd.getFile();
			frm.loadFile(filename);
			
		}else if(cmd.equals("저장")) {	
		
		}else if(cmd.equals("종료")) {
			frm.dispose();
			System.exit(0);
		}else {
			frm.newfile();
		}
	}
}
