//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Address.java
//  @ Date : 2019-07-04
//  @ Author : 
//
//




public class Address {
	public String name;
	public int age;
	public int sex;
	public String address;
	public String phonenumber;
	public String email;
	public void find() {
	
	}
	
	public void findall() {
	
	}
	
	public void registration() {
	
	}
	
	public void revise() {
	
	}
	
	public void remove() {
	
	}
	
	public void quit() {
	
	}
}
